### ISSUE TITLE
Choose Editor

### ISSUE THREAD

**Issue by nkxxll** [Horryportier/openup#2]
How do you want to go about choosing the Editor?
My idea would be to use the `$EDITOR` environment variable as default if it is not empty.
Else you could use vi or something common.

And if you want to change the editor:
* make a keybinding for the list like 'c - change editor'
* make a new model for user input
* set the editor to the new editor (you could even check with `which $(editor)` whether the editor exists on the system)

What do you think?

**Comment by Horryportier** [comment]
About choosing editor.
I thought about list of options saved in json that user would choose from. For now i don't want to over complicate so i would like to stick to simplest way there is but, if u want u can implement cheeking for editor and stuff like that

Model for user input: 
Already written big chunk of it. Only not implemented functions are **adding item** to list and  better looking style 

Branches:
I don't know much about working with others, so i have question 
I've been pushing all changes on main but, I should probably make new branch when I'm adding stuff. What u  think.

**Comment by nkxxll** [comment]
Branches:
I am also new to working with others on git, just wanted to get a little bit into open source, and I really liked your idea for this project.
I think normally you make a "feature branch" when adding some new functionality. When the new functionality has no bugs any more and works fine and as you want it to, the feature branch can be merged into the main branch.

Editor:
If I find some time tomorrow (I am a little bit packed with school stuff at the moment), I will see what I can do for editor checking and default editor. I think I have a good idea for that, which is not that complicated.

Else:
I like the new README :+1: ;-)

**Comment by Horryportier** [comment]
# Branches: 
For now i've been making minimum viable prototype  so I'm letting some bugs go though, so I can put PR request on inspo. After that this code needs a lot of cleaning ;).

# Editor:
for now its just non interactive list that u can choose by typing number of editor. And only one working without any problems are vim and neovim. Vs code has problems with opening directores and I didn't test or even adedd others for now. So that needs aspect needs more work to be done.

# Else: 
- for bugs there is `BUGS.md` file in  `v1` folder.
-  We need some style ideas, now its all stock bubbletea style 
- Maybe some logo.

**Comment by nkxxll** [comment]
#8 

Had some time on my hands today made the default editor work...
